server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
spring:
  application:
    name: k8s-spring-boot
vcap:
  env:
    user:
      name: ${SECRETS_DEMO_USER:humpty}
      password: ${SECRETS_DEMO_USER_PASSWD:dumpty}
