apiVersion: v1
kind: Deployment
metadata:
  name: k8-spring-boot-deployment
  labels:
    app: k8-spring-boot-deployment
spec:
  # tell deployment # of pods to run using the template provided
  replicas: 1
  # use k8-spring-boot-app as the template
  template: 
    metadata:
      app: k8-spring-boot-service
    # breakdown of the container(s)  
    spec:
      # list of volumes
      volumes:
      - name: redis-persistent-storage
        emptyDir: {}
  
      # breakdown of containers in k8s cluster
      containers:
      - name: web
        image: askxtreme:k8-spring-boot
        ports:
        - containerPort: 8080
      - name: redis
        image: redis
        volumeMout:
        - name: redis-persistent-storage
          mountPath: /data/redis
    