apiVersion: v1
kind: Service
metadata:
  name: k8-spring-boot-service
  labels:
    app: k8-spring-boot-service
spec:
  ports: 
    - port: 8080
      targetPort: 8080
  selector:
    app: k8-spring-boot-service
  type: NodeService
