kind: Service
apiVersion: v1
metadata:
  name: k8-spring-boot-service
  labels:
    app: k8-spring-boot
spec:
  selector:
    app: k8-spring-boot
  ports: 
    - port: 8080
      targetPort: 8080
  type: NodePort
